fastlane_version "1.107.0"
default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(scheme: 'VerifyIosSdk_Example_PushEnabled')
    pilot
  end
end
